# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Personal blog of Xiuyu Li, aka nickleefly
email: nickleefly@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A blog from nickleefly(Xiuyu Li).
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://nickleefly.github.io" # the base hostname & protocol for your site
twitter_username: nickleefly
github_username:  nickleefly

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
paginate: 4
paginate_path: "/page/:num/"

gems :
  - jekyll-paginate
